/*
    Copyright 2023 - Present Anton Kudruk
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

import { groupAndSortImports } from "./import_processing";
import { MethodUsageInfo } from "./method_finder";
import { parseQuotedTypeNameLiteral } from "./typeName";

function removeSelfImports(methodUsages: MethodUsageInfo[]): MethodUsageInfo[] {
  return methodUsages.map((usage) => ({
    ...usage,
    imports: usage.imports.filter((importInfo) => importInfo.modulePath !== "generated/generated-cards.d.ts"),
  }));
}

function mergeAsUnion(values: string[], fallback: string): string {
    const uniqueValues = Array.from(new Set(values.filter((value) => !!value && value !== "undefined")));
    if (uniqueValues.length === 0) {
        return fallback;
    }

    if (uniqueValues.length === 1) {
        return uniqueValues[0];
    }

    return uniqueValues.map((value) => `(${value})`).join(" | ");
}

function mergeCardArgumentTypes(argumentTypesList: Record<string, string>[]): Record<string, string> {
    return {
        typeName: argumentTypesList[0]?.typeName,
        nested: mergeAsUnion(argumentTypesList.map((types) => types.nested), "never"),
        attrs: mergeAsUnion(argumentTypesList.map((types) => types.attrs), "never"),
    };
}

function getMergedArgumentTypesByTypeName(methodUsages: MethodUsageInfo[]): Record<string, string>[] {
    const groupedArgumentTypes = new Map<string, Record<string, string>[]>();
    for (const usage of methodUsages) {
        const argumentTypes = usage.argumentTypes;
        const typeName = argumentTypes.typeName;
        if (!typeName || typeName === "undefined") {
            continue;
        }

        const existing = groupedArgumentTypes.get(typeName) ?? [];
        existing.push(argumentTypes);
        groupedArgumentTypes.set(typeName, existing);
    }

    return Array.from(groupedArgumentTypes.values()).map((group) => mergeCardArgumentTypes(group));
}

function generateCardType(argumentTypes: Record<string, string>) {
    const typeName = argumentTypes["typeName"];
    if(!typeName) {
        throw "The type may be generated only for named cards";
    }
    const nested = argumentTypes["nested"] || 'never';
    const attrs = argumentTypes["attrs"] || 'never';
    const result = `interface ${parseQuotedTypeNameLiteral(typeName)} extends Card<${nested}, ${typeName}, ${attrs}> {}`;
    return result;
}

function generateCardTypes(methodUsages: MethodUsageInfo[]) {
    const result = getMergedArgumentTypesByTypeName(methodUsages)
        .map(t => generateCardType(t))
        .map(t => `\t\t${t}`)
        .join("\n");
    return result;
}

function generateGenCardsEntry(cardType: string) {
  const typeName = parseQuotedTypeNameLiteral(cardType);
  const result = `  "${typeName}": GenCardTypes.${typeName},`;
  return result;
}

function generateCardEntries(methodUsages: MethodUsageInfo[]) {
  const result = getMergedArgumentTypesByTypeName(methodUsages)
    .map(t => generateGenCardsEntry(t.typeName))
    .map(t => `\t\t${t}`)
    .join("\n");
  return result;
}

export function generateCardFileContent(methodUsages: MethodUsageInfo[]) {
  const prettyImports = groupAndSortImports(removeSelfImports(methodUsages));
  const importsFromNodeModules = 
    prettyImports
    .external
    .map(i => `import { ${i.typeNames.join(', ')} } from "${i.modulePath}";`)
    .join("\n");

  const importsFromProject = 
    prettyImports
    .internal
    .map(i => `import { ${i.typeNames.join(', ')} } from "${i.modulePath}";`)
    .join("\n");

  const result = `
/*
The file is generated by XorLAB preprocessor.
Don't update it manually.

Segment and card typeName values must be globally unique within a preprocessed project.
*/

import {ICard, Card, ISeg, Seg} from "xorlab";

${importsFromNodeModules}

${importsFromProject}

declare global {
  export interface GenCards {
${generateCardEntries(methodUsages)}
  }

  export namespace GenCardTypes {
${generateCardTypes(methodUsages)}
  }
}

export {};
  `;

  return result;
}
